name: pcg-rnn-analysis
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.12.1
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - pytorch
  - jupyter
  - ipykernel
  - pip
  - pip:
    - mat73
    - hydra-core
